In [1]:
import numpy as np
from scipy.spatial.transform import Rotation
transform = {
    "cam0_camera_base":np.array([
        [
            -0.7832018455811732,
            -0.3175976553526907,
            -0.5345340011568185,
            1.97201649
        ],
        [
            0.15946127661890502,
            -0.9335475391651192,
            0.3210312965706292,
            -0.14115217
        ],
        [
            -0.600971688465699,
            0.16619482974275618,
            0.781800683185595,
            1.27146159
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ]),
    "ra_base_link":np.array([
        [
            1.0,
            0.0,
            0.0,
            0.0
        ],
        [
            0.0,
            1.0,
            0.0,
            0.0
        ],
        [
            0.0,
            0.0,
            1.0,
            0.7551
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ])
    ,"ICP_transform":np.array(
        [
            [0.999450, -0.001704, -0.033131, 0.022731],
            [0.001350, 0.999942, -0.010717, 0.008886],
            [0.033148, 0.010666, 0.999394, -0.025385],
            [0.000000, 0.000000, 0.000000, 1.000000]
        ]
    ),
    "cam0_rgb_link":np.array([
        [
            0.31842582813078124,
            0.5476966118699068,
            -0.7737140384699324,
            1.9855345041922787
        ],
        [
            0.9331753409732655,
            -0.32464135256597637,
            0.15424582718363705,
            -0.11211594046023274
        ],
        [
            -0.16669965500461342,
            -0.7711267169216478,
            -0.6144711640679202,
            1.2681138982911153
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ])
}


correct_result = transform["ICP_transform"] @ transform["cam0_rgb_link"]
cam0_base_link2cam0depth_link = np.linalg.inv(transform["cam0_camera_base"])@transform["cam0_rgb_link"]

ra_base_ling2cam0_base_link = np.linalg.inv(transform["ra_base_link"])@correct_result @np.linalg.inv(cam0_base_link2cam0depth_link)
print(ra_base_ling2cam0_base_link[:3,3])
quer = Rotation.from_matrix(ra_base_ling2cam0_base_link[:3,:3]).as_quat()
print(quer[[0,1,2,3]])

[ 1.95177861 -0.14322201  0.55406896]
[-0.31840981  0.12287842  0.93084188  0.13057362]


In [2]:
[ 1.96624209 -0.11517305  0.54985838]
[-0.27725376  0.11733101  0.94380295  0.13638099]

SyntaxError: invalid syntax (4233721700.py, line 1)