In [1]:
import numpy as np

from scipy.spatial.transform import Rotation

In [2]:
cam0_rgb_camera_link =  np.array([
        [
            0.31842582813078124,
            0.5476966118699068,
            -0.7737140384699324,
            1.9855345041922787
        ],
        [
            0.9331753409732655,
            -0.32464135256597637,
            0.15424582718363705,
            -0.11211594046023274
        ],
        [
            -0.16669965500461342,
            -0.7711267169216478,
            -0.6144711640679202,
            1.2681138982911153
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ])

In [3]:
model_transform = np.array([
    [-0.211521 ,-0.367137 ,0.905798 ,0.946677] ,
    [0.445006 ,-0.861309 ,-0.245188 ,0.192903 ],
    [0.870189 ,0.351223 ,0.345563 ,0.715193 ],
    [0.000000 ,0.000000, 0.000000 ,1.000000 ]
])

In [4]:
result_transoform = np.linalg.inv(cam0_rgb_camera_link)@model_transform

In [5]:
print(result_transoform)

[[ 0.20285467 -0.97920698  0.00202085  0.04600882]
 [-0.93134267 -0.19230061  0.3092278  -0.24162842]
 [-0.30240896 -0.06461067 -0.95098635  1.19058048]
 [ 0.          0.          0.          1.        ]]


In [6]:
quat = Rotation.from_matrix(result_transoform[:3,:3])
print(quat.as_quat()[[3,0,1,2]])
print(result_transoform[:3,3])

[-0.12203287  0.76585591 -0.62366471 -0.09805632]
[ 0.04600882 -0.24162842  1.19058048]
