In [1]:
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
def transform_mesh_with_matrix(transform_matrix,mesh):
    vertices = np.asarray(mesh.vertices).copy() 
    vertices = np.hstack((vertices,np.ones((vertices.shape[0],1))),dtype=float).T
    transformed_vertices = np.dot(transform_matrix[:3,:],vertices).T
    mesh.vertices = o3d.utility.Vector3dVector(transformed_vertices)
    return mesh


In [3]:
rgb_transform_matrix = np.array(
[       

        [
            0.31842582813078124,
            0.5476966118699068,
            -0.7737140384699324,
            1.9855345041922787
        ],
        [
            0.9331753409732655,
            -0.32464135256597637,
            0.15424582718363705,
            -0.11211594046023274
        ],
        [
            -0.16669965500461342,
            -0.7711267169216478,
            -0.6144711640679202,
            1.2681138982911153
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    
        ]
)
depth_transform_matrix = np.array(
    [
        [
            0.31759765535269063,
            0.6134726533162566,
            -0.7230373662180857,
            1.9710543288144453
        ],
        [
            0.9335475391651196,
            -0.3359408957336286,
            0.12503082296952778,
            -0.14057431367609913
        ],
        [
            -0.16619482974275596,
            -0.7146992501792624,
            -0.6793999266705708,
            1.2728688312055607
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ]
)
transform_matrix = np.dot(rgb_transform_matrix,np.linalg.inv(depth_transform_matrix))
print(transform_matrix)


[[ 0.99655235  0.01653385  0.08130218 -0.07988709]
 [-0.01430979  0.99950933 -0.02786259  0.09206019]
 [-0.08172296  0.02660311  0.99629997  0.16477483]
 [ 0.          0.          0.          1.        ]]


In [4]:
mesh = o3d.io.read_triangle_mesh("/home/tony/mine/Projects/ArmHandVis/HandVersion/HandArmFiles/ARM_HAND_URDF/yyx_tmp/hand_ICP/hand_ICP_backup/3/transform_environment.ply")
mesh = transform_mesh_with_matrix(transform_matrix,mesh)
o3d.io.write_triangle_mesh("/home/tony/mine/Projects/ArmHandVis/HandVersion/HandArmFiles/ARM_HAND_URDF/yyx_tmp/hand_ICP/hand_ICP_backup/3/normal_environment.ply",mesh)

[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).


True